### ISSUE TITLE
Seems not working with Rails Spring

### ISSUE THREAD

**Issue by lazywei** [r7kamura/autodoc#28]
Hi,

I'm trying to use this with [spring](rails/spring) like this:

```
AUTODOC=1 spring rspec  --color  spec/requests/users_spec.rb
```

but it generates nothing.

I need to use it without spring like this

```
AUTODOC=1 rspec  --color  spec/requests/users_spec.rb:19
```

to make it generate docs.

I'm not sure if this is autodoc's or spring's issue?
Thanks

**Comment by r7kamura** [comment]
hmm, I have no idea what is going on spring because spring has a lot of issues in integrations with other libraries and I'm not using it, however, https://github.com/r7kamura/autodoc/blob/45e81d54d67b414d3fd4b1e3286bd429e5cc858b/lib/autodoc.rb#L5 or https://github.com/r7kamura/autodoc/blob/45e81d54d67b414d3fd4b1e3286bd429e5cc858b/lib/autodoc/rspec.rb might be related to this issue. Probably you may be able to work autodoc with spring by `require "autodoc/rspec"` in your spec_helper.rb.

**Comment by lazywei** [comment]
Got it. I think the problem should be on spring's side.
Thanks for the information. I think I can use that workaround.

By the way, a little off-topic, do you have any other recommended rails preloader other than spring then?

Thanks.

**Comment by r7kamura** [comment]
I have tried [burke/zeus](https://github.com/burke/zeus), [sporkrb/spork](https://github.com/sporkrb/spork), [nviennot/rspec-console](https://github.com/nviennot/rspec-console), and [rails/spring](https://github.com/rails/spring), but any of these were confusing in some cases. (e.g. they have poor imcompatibility with fixture replacement like [thoughtbot/factory_girl](https://github.com/thoughtbot/factory_girl) and [notahat/machinist](https://github.com/notahat/machinist)). Finally I'm not using any rails preloader and keep each test fast by separating spec_helper.rb & [rails_helper.rb](https://www.relishapp.com/rspec/rspec-rails/docs/upgrade).
